# Generated by Django 5.0.2 on 2025-12-10 17:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversationmessage',
            name='content',
        ),
        migrations.AddField(
            model_name='conversationmessage',
            name='body',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='conversationmessage',
            name='sent_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL),
        ),
    ]
